services:
  - type: web
    name: audio-analysis-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000
    scaling:
      minInstances: 1
      maxInstances: 3
