services:
  - type: web
    name: audio-analysis-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000
      - key: MAX_CONTENT_LENGTH
        value: 16777216
    healthCheckPath: /health
    autoDeploy: true
